trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  packageVersion: '0.1.0'


steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build'
- script: dotnet test --configuration $(buildConfiguration)
  displayName: 'dotnet test'
- script: dotnet pack --configuration $(buildConfiguration)
  displayName: 'dotnet pack'
- task: NuGetCommand@2
  displayName: 'dotnet nuget publish'
  inputs:
    command: 'push'
    packagesToPush: './App/bin/$(buildConfiguration)/Badgie.Migrator.$(packageVersion).nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '/e1b49793-88dd-47fb-9e13-59e4ffa1c1a3'
