trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build'
- script: dotnet test --configuration $(buildConfiguration)
  displayName: 'dotnet test'
- script: dotnet pack --configuration $(buildConfiguration)
  displayName: 'dotnet pack'
- script: dotnet nuget push -Source "Badgiet" -ApiKey AzureDevOps ./App/bin/Release/Badgine.Migrator.0.1.0.nupkg
  displayName: 'dotnet nuget push'
